spring.application.name=brewpos-backend
server.port=8081

# ========== EMAIL (Gmail SMTP example) ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jala.fumar.sjc@phinmaed.com
spring.mail.password=sosjgfsqaclougkc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Debug logs (temporary)
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

removebg.apiKey=Bp8jWWFZWFx57GmEn7QgZNBr

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# where to save uploaded images (choose one)
app.upload.dir=uploads
# app.upload.dir=C:/brewpos_uploads
app.publicBaseUrl=http://192.168.254.105:8081

